name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js 14.x to Build
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: tmux
    - run: npm install
    - run: CI=false npm run start
    
    - name: ssh deploy on aws ec2
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST_DNS: ${{ secrets.HOST_DNS }}
        USERNAME: ${{ secrets.USERNAME }}
        TARGET_DIR: ${{ secrets.TARGET_DIR }}
          
